% [Data, file_names, colnames, line_3, line_1]=HL_DLCUtil_ReadLabeledCSV(csv_fn)
% function to read in .csv files generated by DLC when labeling data
%
% INPUT:
%   csv_fn: .csv file fullpath
% OUTPUT:
%   Data: -struct with subfields as the object names
%         .(part_name).x, .y, 
%   file_names: corresponding file name for each labeled picture
%   colnames:
%   line_3: 

function [Data, file_names, colnames, line_3, line_1]=HL_DLCUtil_ReadLabeledCSV(csv_fn)
Data = [];
fh = fopen(csv_fn);
line_1 = strsplit(fgetl(fh),',');  % skip the first line
colnames = strsplit(fgetl(fh),','); %extract column names
line_3 = strsplit(fgetl(fh),','); %line 3

k = 1;
temp = strsplit(fgetl(fh),','); %next line
file_names{k} = temp{1};    
k = k+1;
% data{k} = strsplit(fgetl(fh),','); %next line %% this will skip
% empty/space entry

% read the first cell of each line until the file end: file names
while ~feof(fh) % not the end
    temp = strsplit(fgetl(fh),','); %next line
    file_names{k} = temp{1};
    k = k+1;
end
fclose(fh);

M = csvread(csv_fn, 3,1); % read in all the numbers

% check if match
if length(file_names) ~= size(M,1)
    error('image file name # does not match labeled file number')
end

for i_part = 1:(length(colnames)-1)/2 % skip the first column which is frame number & x y coor
    %set ori
    Data.(colnames{2*(i_part-1)+1+1}).x = M(:,1+2*(i_part-1));
    Data.(colnames{2*(i_part-1)+1+1}).y = M(:,1+1+2*(i_part-1));
end